"""Bundled, prebuilt firmware images shipped inside the wheel.

The actual ``*.bin`` here is a merged "Huge APP" (3 MB app, no OTA) build of
``examples/Bridge`` for the classic ESP32 — a single image written at flash
offset 0x0. It is *not* committed to git; it is regenerated by
``tools/build_firmware.py`` (run in CI before ``uv build``, or locally), so a
plain source checkout may not contain it. ``espbridge.flash`` locates it via
``importlib.resources`` and writes it to a board with esptool, letting users
flash the firmware without opening the Arduino IDE.
"""
